// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: auditproxy/v1/access.proto

package auditproxyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessDecisionService_Authenticate_FullMethodName            = "/auditproxy.v1.AccessDecisionService/Authenticate"
	AccessDecisionService_AuthorizeSession_FullMethodName        = "/auditproxy.v1.AccessDecisionService/AuthorizeSession"
	AccessDecisionService_AuthorizeChannel_FullMethodName        = "/auditproxy.v1.AccessDecisionService/AuthorizeChannel"
	AccessDecisionService_AuthorizeCommand_FullMethodName        = "/auditproxy.v1.AccessDecisionService/AuthorizeCommand"
	AccessDecisionService_ResolveHostKey_FullMethodName          = "/auditproxy.v1.AccessDecisionService/ResolveHostKey"
	AccessDecisionService_IssueUpstreamCredential_FullMethodName = "/auditproxy.v1.AccessDecisionService/IssueUpstreamCredential"
	AccessDecisionService_OpenSession_FullMethodName             = "/auditproxy.v1.AccessDecisionService/OpenSession"
	AccessDecisionService_HeartbeatSession_FullMethodName        = "/auditproxy.v1.AccessDecisionService/HeartbeatSession"
	AccessDecisionService_CloseSession_FullMethodName            = "/auditproxy.v1.AccessDecisionService/CloseSession"
	AccessDecisionService_StreamRevocations_FullMethodName       = "/auditproxy.v1.AccessDecisionService/StreamRevocations"
	AccessDecisionService_ReportEvents_FullMethodName            = "/auditproxy.v1.AccessDecisionService/ReportEvents"
	AccessDecisionService_GetPolicySnapshot_FullMethodName       = "/auditproxy.v1.AccessDecisionService/GetPolicySnapshot"
)

// AccessDecisionServiceClient is the client API for AccessDecisionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccessDecisionService is the policy decision point the SSH data plane calls.
//
// The data plane terminates connections and moves bytes; it does not hold the
// policy or the credentials. Every question that could grant or widen access —
// who is this, may they reach that host, as which account, with which
// capabilities, and may they run this command — is answered here, against the
// database, at the moment it is asked. That is what makes a revocation take
// effect on the next decision instead of the next configuration reload.
type AccessDecisionServiceClient interface {
	// Authenticate runs one step of the SSH authentication exchange. Multi-round
	// methods such as keyboard-interactive call it repeatedly, carrying the
	// state handle the previous response returned.
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	// AuthorizeSession decides whether an authenticated principal may open a
	// session to a target, and returns the constraints it must run under.
	AuthorizeSession(ctx context.Context, in *AuthorizeSessionRequest, opts ...grpc.CallOption) (*AuthorizeSessionResponse, error)
	// AuthorizeChannel gates each channel a client opens, so that a session
	// permitted to run a shell cannot also open a tunnel unless policy says so.
	AuthorizeChannel(ctx context.Context, in *AuthorizeChannelRequest, opts ...grpc.CallOption) (*AuthorizeChannelResponse, error)
	// AuthorizeCommand screens a command before it reaches the upstream host.
	//
	// It streams because a command may require a second person's approval: the
	// first response reports that the session is waiting, and a later one carries
	// the outcome. A single unary call would either have to block a connection
	// for minutes or give up the ability to hold one.
	AuthorizeCommand(ctx context.Context, in *AuthorizeCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuthorizeCommandResponse], error)
	// ResolveHostKey checks a host key presented by an upstream against the trust
	// store, and records first-contact keys for an operator to rule on.
	ResolveHostKey(ctx context.Context, in *ResolveHostKeyRequest, opts ...grpc.CallOption) (*ResolveHostKeyResponse, error)
	// IssueUpstreamCredential hands back the material needed to authenticate to
	// the upstream host for one session. Short-lived certificates are preferred;
	// stored secrets are decrypted here and never persisted by the data plane.
	IssueUpstreamCredential(ctx context.Context, in *IssueUpstreamCredentialRequest, opts ...grpc.CallOption) (*IssueUpstreamCredentialResponse, error)
	// Session lifecycle. Sessions live in the shared database so that any node
	// can enumerate and terminate a session another node is serving.
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error)
	HeartbeatSession(ctx context.Context, in *HeartbeatSessionRequest, opts ...grpc.CallOption) (*HeartbeatSessionResponse, error)
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
	// StreamRevocations pushes termination requests to the node that owns the
	// affected sessions. Heartbeats also carry the flag, so a node still learns
	// about a revocation if this stream is interrupted.
	StreamRevocations(ctx context.Context, in *StreamRevocationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Revocation], error)
	// ReportEvents ships audit records. The data plane spools locally and
	// replays, so a control-plane outage delays delivery rather than losing it.
	ReportEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AuditEventBatch, ReportEventsResponse], error)
	// GetPolicySnapshot returns the rules a node needs to keep serving while the
	// control plane is unreachable, for deployments that choose availability over
	// strict centralisation.
	GetPolicySnapshot(ctx context.Context, in *PolicySnapshotRequest, opts ...grpc.CallOption) (*PolicySnapshot, error)
}

type accessDecisionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessDecisionServiceClient(cc grpc.ClientConnInterface) AccessDecisionServiceClient {
	return &accessDecisionServiceClient{cc}
}

func (c *accessDecisionServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, AccessDecisionService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessDecisionServiceClient) AuthorizeSession(ctx context.Context, in *AuthorizeSessionRequest, opts ...grpc.CallOption) (*AuthorizeSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeSessionResponse)
	err := c.cc.Invoke(ctx, AccessDecisionService_AuthorizeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessDecisionServiceClient) AuthorizeChannel(ctx context.Context, in *AuthorizeChannelRequest, opts ...grpc.CallOption) (*AuthorizeChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeChannelResponse)
	err := c.cc.Invoke(ctx, AccessDecisionService_AuthorizeChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessDecisionServiceClient) AuthorizeCommand(ctx context.Context, in *AuthorizeCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuthorizeCommandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccessDecisionService_ServiceDesc.Streams[0], AccessDecisionService_AuthorizeCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AuthorizeCommandRequest, AuthorizeCommandResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccessDecisionService_AuthorizeCommandClient = grpc.ServerStreamingClient[AuthorizeCommandResponse]

func (c *accessDecisionServiceClient) ResolveHostKey(ctx context.Context, in *ResolveHostKeyRequest, opts ...grpc.CallOption) (*ResolveHostKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveHostKeyResponse)
	err := c.cc.Invoke(ctx, AccessDecisionService_ResolveHostKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessDecisionServiceClient) IssueUpstreamCredential(ctx context.Context, in *IssueUpstreamCredentialRequest, opts ...grpc.CallOption) (*IssueUpstreamCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueUpstreamCredentialResponse)
	err := c.cc.Invoke(ctx, AccessDecisionService_IssueUpstreamCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessDecisionServiceClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenSessionResponse)
	err := c.cc.Invoke(ctx, AccessDecisionService_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessDecisionServiceClient) HeartbeatSession(ctx context.Context, in *HeartbeatSessionRequest, opts ...grpc.CallOption) (*HeartbeatSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatSessionResponse)
	err := c.cc.Invoke(ctx, AccessDecisionService_HeartbeatSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessDecisionServiceClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, AccessDecisionService_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessDecisionServiceClient) StreamRevocations(ctx context.Context, in *StreamRevocationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Revocation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccessDecisionService_ServiceDesc.Streams[1], AccessDecisionService_StreamRevocations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRevocationsRequest, Revocation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccessDecisionService_StreamRevocationsClient = grpc.ServerStreamingClient[Revocation]

func (c *accessDecisionServiceClient) ReportEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AuditEventBatch, ReportEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccessDecisionService_ServiceDesc.Streams[2], AccessDecisionService_ReportEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AuditEventBatch, ReportEventsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccessDecisionService_ReportEventsClient = grpc.ClientStreamingClient[AuditEventBatch, ReportEventsResponse]

func (c *accessDecisionServiceClient) GetPolicySnapshot(ctx context.Context, in *PolicySnapshotRequest, opts ...grpc.CallOption) (*PolicySnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicySnapshot)
	err := c.cc.Invoke(ctx, AccessDecisionService_GetPolicySnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessDecisionServiceServer is the server API for AccessDecisionService service.
// All implementations must embed UnimplementedAccessDecisionServiceServer
// for forward compatibility.
//
// AccessDecisionService is the policy decision point the SSH data plane calls.
//
// The data plane terminates connections and moves bytes; it does not hold the
// policy or the credentials. Every question that could grant or widen access —
// who is this, may they reach that host, as which account, with which
// capabilities, and may they run this command — is answered here, against the
// database, at the moment it is asked. That is what makes a revocation take
// effect on the next decision instead of the next configuration reload.
type AccessDecisionServiceServer interface {
	// Authenticate runs one step of the SSH authentication exchange. Multi-round
	// methods such as keyboard-interactive call it repeatedly, carrying the
	// state handle the previous response returned.
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	// AuthorizeSession decides whether an authenticated principal may open a
	// session to a target, and returns the constraints it must run under.
	AuthorizeSession(context.Context, *AuthorizeSessionRequest) (*AuthorizeSessionResponse, error)
	// AuthorizeChannel gates each channel a client opens, so that a session
	// permitted to run a shell cannot also open a tunnel unless policy says so.
	AuthorizeChannel(context.Context, *AuthorizeChannelRequest) (*AuthorizeChannelResponse, error)
	// AuthorizeCommand screens a command before it reaches the upstream host.
	//
	// It streams because a command may require a second person's approval: the
	// first response reports that the session is waiting, and a later one carries
	// the outcome. A single unary call would either have to block a connection
	// for minutes or give up the ability to hold one.
	AuthorizeCommand(*AuthorizeCommandRequest, grpc.ServerStreamingServer[AuthorizeCommandResponse]) error
	// ResolveHostKey checks a host key presented by an upstream against the trust
	// store, and records first-contact keys for an operator to rule on.
	ResolveHostKey(context.Context, *ResolveHostKeyRequest) (*ResolveHostKeyResponse, error)
	// IssueUpstreamCredential hands back the material needed to authenticate to
	// the upstream host for one session. Short-lived certificates are preferred;
	// stored secrets are decrypted here and never persisted by the data plane.
	IssueUpstreamCredential(context.Context, *IssueUpstreamCredentialRequest) (*IssueUpstreamCredentialResponse, error)
	// Session lifecycle. Sessions live in the shared database so that any node
	// can enumerate and terminate a session another node is serving.
	OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error)
	HeartbeatSession(context.Context, *HeartbeatSessionRequest) (*HeartbeatSessionResponse, error)
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	// StreamRevocations pushes termination requests to the node that owns the
	// affected sessions. Heartbeats also carry the flag, so a node still learns
	// about a revocation if this stream is interrupted.
	StreamRevocations(*StreamRevocationsRequest, grpc.ServerStreamingServer[Revocation]) error
	// ReportEvents ships audit records. The data plane spools locally and
	// replays, so a control-plane outage delays delivery rather than losing it.
	ReportEvents(grpc.ClientStreamingServer[AuditEventBatch, ReportEventsResponse]) error
	// GetPolicySnapshot returns the rules a node needs to keep serving while the
	// control plane is unreachable, for deployments that choose availability over
	// strict centralisation.
	GetPolicySnapshot(context.Context, *PolicySnapshotRequest) (*PolicySnapshot, error)
	mustEmbedUnimplementedAccessDecisionServiceServer()
}

// UnimplementedAccessDecisionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessDecisionServiceServer struct{}

func (UnimplementedAccessDecisionServiceServer) Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedAccessDecisionServiceServer) AuthorizeSession(context.Context, *AuthorizeSessionRequest) (*AuthorizeSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeSession not implemented")
}
func (UnimplementedAccessDecisionServiceServer) AuthorizeChannel(context.Context, *AuthorizeChannelRequest) (*AuthorizeChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeChannel not implemented")
}
func (UnimplementedAccessDecisionServiceServer) AuthorizeCommand(*AuthorizeCommandRequest, grpc.ServerStreamingServer[AuthorizeCommandResponse]) error {
	return status.Errorf(codes.Unimplemented, "method AuthorizeCommand not implemented")
}
func (UnimplementedAccessDecisionServiceServer) ResolveHostKey(context.Context, *ResolveHostKeyRequest) (*ResolveHostKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveHostKey not implemented")
}
func (UnimplementedAccessDecisionServiceServer) IssueUpstreamCredential(context.Context, *IssueUpstreamCredentialRequest) (*IssueUpstreamCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueUpstreamCredential not implemented")
}
func (UnimplementedAccessDecisionServiceServer) OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedAccessDecisionServiceServer) HeartbeatSession(context.Context, *HeartbeatSessionRequest) (*HeartbeatSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatSession not implemented")
}
func (UnimplementedAccessDecisionServiceServer) CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedAccessDecisionServiceServer) StreamRevocations(*StreamRevocationsRequest, grpc.ServerStreamingServer[Revocation]) error {
	return status.Errorf(codes.Unimplemented, "method StreamRevocations not implemented")
}
func (UnimplementedAccessDecisionServiceServer) ReportEvents(grpc.ClientStreamingServer[AuditEventBatch, ReportEventsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReportEvents not implemented")
}
func (UnimplementedAccessDecisionServiceServer) GetPolicySnapshot(context.Context, *PolicySnapshotRequest) (*PolicySnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPolicySnapshot not implemented")
}
func (UnimplementedAccessDecisionServiceServer) mustEmbedUnimplementedAccessDecisionServiceServer() {}
func (UnimplementedAccessDecisionServiceServer) testEmbeddedByValue()                               {}

// UnsafeAccessDecisionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessDecisionServiceServer will
// result in compilation errors.
type UnsafeAccessDecisionServiceServer interface {
	mustEmbedUnimplementedAccessDecisionServiceServer()
}

func RegisterAccessDecisionServiceServer(s grpc.ServiceRegistrar, srv AccessDecisionServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccessDecisionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessDecisionService_ServiceDesc, srv)
}

func _AccessDecisionService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessDecisionServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessDecisionService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessDecisionServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessDecisionService_AuthorizeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessDecisionServiceServer).AuthorizeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessDecisionService_AuthorizeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessDecisionServiceServer).AuthorizeSession(ctx, req.(*AuthorizeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessDecisionService_AuthorizeChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessDecisionServiceServer).AuthorizeChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessDecisionService_AuthorizeChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessDecisionServiceServer).AuthorizeChannel(ctx, req.(*AuthorizeChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessDecisionService_AuthorizeCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AuthorizeCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccessDecisionServiceServer).AuthorizeCommand(m, &grpc.GenericServerStream[AuthorizeCommandRequest, AuthorizeCommandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccessDecisionService_AuthorizeCommandServer = grpc.ServerStreamingServer[AuthorizeCommandResponse]

func _AccessDecisionService_ResolveHostKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveHostKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessDecisionServiceServer).ResolveHostKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessDecisionService_ResolveHostKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessDecisionServiceServer).ResolveHostKey(ctx, req.(*ResolveHostKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessDecisionService_IssueUpstreamCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueUpstreamCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessDecisionServiceServer).IssueUpstreamCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessDecisionService_IssueUpstreamCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessDecisionServiceServer).IssueUpstreamCredential(ctx, req.(*IssueUpstreamCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessDecisionService_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessDecisionServiceServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessDecisionService_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessDecisionServiceServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessDecisionService_HeartbeatSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessDecisionServiceServer).HeartbeatSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessDecisionService_HeartbeatSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessDecisionServiceServer).HeartbeatSession(ctx, req.(*HeartbeatSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessDecisionService_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessDecisionServiceServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessDecisionService_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessDecisionServiceServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessDecisionService_StreamRevocations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRevocationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccessDecisionServiceServer).StreamRevocations(m, &grpc.GenericServerStream[StreamRevocationsRequest, Revocation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccessDecisionService_StreamRevocationsServer = grpc.ServerStreamingServer[Revocation]

func _AccessDecisionService_ReportEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AccessDecisionServiceServer).ReportEvents(&grpc.GenericServerStream[AuditEventBatch, ReportEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccessDecisionService_ReportEventsServer = grpc.ClientStreamingServer[AuditEventBatch, ReportEventsResponse]

func _AccessDecisionService_GetPolicySnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicySnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessDecisionServiceServer).GetPolicySnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessDecisionService_GetPolicySnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessDecisionServiceServer).GetPolicySnapshot(ctx, req.(*PolicySnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessDecisionService_ServiceDesc is the grpc.ServiceDesc for AccessDecisionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessDecisionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auditproxy.v1.AccessDecisionService",
	HandlerType: (*AccessDecisionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AccessDecisionService_Authenticate_Handler,
		},
		{
			MethodName: "AuthorizeSession",
			Handler:    _AccessDecisionService_AuthorizeSession_Handler,
		},
		{
			MethodName: "AuthorizeChannel",
			Handler:    _AccessDecisionService_AuthorizeChannel_Handler,
		},
		{
			MethodName: "ResolveHostKey",
			Handler:    _AccessDecisionService_ResolveHostKey_Handler,
		},
		{
			MethodName: "IssueUpstreamCredential",
			Handler:    _AccessDecisionService_IssueUpstreamCredential_Handler,
		},
		{
			MethodName: "OpenSession",
			Handler:    _AccessDecisionService_OpenSession_Handler,
		},
		{
			MethodName: "HeartbeatSession",
			Handler:    _AccessDecisionService_HeartbeatSession_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _AccessDecisionService_CloseSession_Handler,
		},
		{
			MethodName: "GetPolicySnapshot",
			Handler:    _AccessDecisionService_GetPolicySnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AuthorizeCommand",
			Handler:       _AccessDecisionService_AuthorizeCommand_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamRevocations",
			Handler:       _AccessDecisionService_StreamRevocations_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReportEvents",
			Handler:       _AccessDecisionService_ReportEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "auditproxy/v1/access.proto",
}
